---
# tasks file for roles/web
- name: Deploy Nginx Container
  community.docker.docker_container:
    name: nginx
    image: "nginx:{{ web_nginx_version }}"
    ports:
      - "80:80"
    state: started
    volumes:
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart_policy: always
  become: true
  notify: Restart Nginx
  tags:
    - nginx
    - docker
    - deployment
